name: Build and Deploy code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: testing
    env: 
      DATABASE_HOSTNAME: ${{secrets.GITHUB_TOKEN}}
      DATABASE_PORT: ${{secrets.GITHUB_TOKEN}}
      DATABASE_PASSWORD: ${{secrets.GITHUB_TOKEN}}
      DATABASE_NAME: ${{secrets.GITHUB_TOKEN}}
      DATABASE_USERNAME: ${{secrets.GITHUB_TOKEN}}
      SECRET_KEY: ${{secrets.GITHUB_TOKEN}}
      ALGORITHM: ${{secrets.GITHUB_TOKEN}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.GITHUB_TOKEN}}  
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
            pyhton-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies 
        run: pip install -r requirements.txt
      - name: test with Pytest
        run: |
          pip install pytest
          pytest
          
